name: igs-assetadmin-service
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.7.2'

      - name: install dependencies
        run: npm install
        
      - name: Execute commands over SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/emp-fe-demo
            rm -rf*
            sudo -s docker stop master-fe
            cd /home/ubuntu/emp-fe-demo
            cp /home/ubuntu/fe/.env .
            cp /home/ubuntu/fe/* .
           
      - name: deployment to servert and dockerrizing the application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
              cd /home/ubuntu/emp-fe-demo
              sudo docker build -t emp-fe-demo:latest .
              sudo docker run --name master-fe -d -p 3003:80 emp-fe-demo:latest .

            
