name: emp-fe-demo
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.7.2'  # Keep Node.js version as specified
 
      - name: Install dependencies
        working-directory: ./
        run: npm install
 
      - name: Execute commands over SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            /usr/local/bin/pm2 kill
            cd /home/ubuntu/igs-AdminAssetMgr-services
            sudo rm -rf *
 
      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "igs-AdminAssetMgr-services/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}  
          TARGET: /home/ubuntu/igs-AdminAssetMgr-services/
 
 
      - name: Restart PM2 Process
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu
            /usr/local/bin/pm2 start ecosystem.config.js
